name: Release Database Connector Service
on:
  push:
    tags:
      - 'v*' # P

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Installing catalyst
        run : npm i -g zcatalyst-cli
      - name: Creating 'Release' Directory
        run: mkdir -p release/functions
      - name: Installing Packages for 'v1' & Creating the Zip
        run: cd functions/v1/ && npm install --omit=dev && zip -r ../../release/functions/v1.zip .
      - name: Deploying code to catalyst
        run: catalyst deploy --only fuctions:v1 -p ${{ secrets.CATALYST_PROJECT_NAME}} --org ${{ secrets.CATALYST_ORG}} --token ${{ secrets.CATALYST_TOKEN}}

      # - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          artifacts: './release/release.zip'
          bodyFile: 'README.md'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.RELEASE_VERSION }}